version: '2'
services:
  stub:
    image: sg248351/stub
    ports:
      - "4414:4414"
      - "7800:7800"
    environment:
      - LICENSE=accept
    networks:
      sc1-net:
        aliases:
          - stub

  sgw:
    build: ./
    image: sg248351/secure-gateway-client
    depends_on:
      - stub
    command: [3lbCuQT45x4_prod_ng, -F, /tmp/aclfile.txt, --sectoken, eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb25maWd1cmF0aW9uX2lkIjoiM2xiQ3VRVDQ1eDRfcHJvZF9uZyIsInJlZ2lvbiI6InVzLXNvdXRoIiwiaWF0IjoxNDczNjc5ODgxfQ.3rVzly0EA6aXvg0CIttDb4ABzVrJJc7CdWUDyyq1dMQ]
    networks:
      sc1-net:
        aliases:
          - sgw

networks:
  sc1-net:
    driver: bridge
